"""
Runtime paths for files generated by the backend.
"""
import os
from pathlib import Path

BACKEND_DIR = Path(__file__).resolve().parents[1]
PROJECT_ROOT = BACKEND_DIR.parent

UPLOAD_DIR = Path(os.getenv("CODEWRIGHT_UPLOAD_DIR", PROJECT_ROOT / "upload"))
TEMPLATES_DIR = Path(os.getenv("CODEWRIGHT_TEMPLATES_DIR", PROJECT_ROOT / "templates"))
EXPORTS_DIR = Path(os.getenv("CODEWRIGHT_EXPORTS_DIR", PROJECT_ROOT / "exports"))
RUNTIME_DIR = Path(os.getenv("CODEWRIGHT_RUNTIME_DIR", PROJECT_ROOT / ".runtime"))
TINYTEX_DIR = Path(os.getenv("CODEWRIGHT_TINYTEX_DIR", RUNTIME_DIR / "tinytex"))
TINYTEX_DOWNLOAD_DIR = Path(os.getenv("CODEWRIGHT_TINYTEX_DOWNLOAD_DIR", RUNTIME_DIR / "downloads"))


def ensure_runtime_dirs() -> None:
    """Create directories required by uploads, templates, and exports."""
    for path in (UPLOAD_DIR, TEMPLATES_DIR, EXPORTS_DIR, RUNTIME_DIR):
        path.mkdir(parents=True, exist_ok=True)
